// Common grocery items for fuzzy-match autocomplete suggestions
// Categories match pantryCategories.js

export const GROCERY_ITEMS = [
  // Dairy
  { name: "milk", category: "Dairy" },
  { name: "whole milk", category: "Dairy" },
  { name: "skim milk", category: "Dairy" },
  { name: "oat milk", category: "Dairy" },
  { name: "almond milk", category: "Dairy" },
  { name: "butter", category: "Dairy" },
  { name: "eggs", category: "Dairy" },
  { name: "cheese", category: "Dairy" },
  { name: "cheddar cheese", category: "Dairy" },
  { name: "mozzarella cheese", category: "Dairy" },
  { name: "parmesan cheese", category: "Dairy" },
  { name: "cream cheese", category: "Dairy" },
  { name: "cottage cheese", category: "Dairy" },
  { name: "yogurt", category: "Dairy" },
  { name: "greek yogurt", category: "Dairy" },
  { name: "sour cream", category: "Dairy" },
  { name: "heavy cream", category: "Dairy" },
  { name: "half and half", category: "Dairy" },
  { name: "whipped cream", category: "Dairy" },

  // Produce
  { name: "apples", category: "Produce" },
  { name: "bananas", category: "Produce" },
  { name: "oranges", category: "Produce" },
  { name: "lemons", category: "Produce" },
  { name: "limes", category: "Produce" },
  { name: "grapes", category: "Produce" },
  { name: "strawberries", category: "Produce" },
  { name: "blueberries", category: "Produce" },
  { name: "raspberries", category: "Produce" },
  { name: "avocado", category: "Produce" },
  { name: "tomatoes", category: "Produce" },
  { name: "potatoes", category: "Produce" },
  { name: "sweet potatoes", category: "Produce" },
  { name: "onions", category: "Produce" },
  { name: "garlic", category: "Produce" },
  { name: "ginger", category: "Produce" },
  { name: "carrots", category: "Produce" },
  { name: "celery", category: "Produce" },
  { name: "broccoli", category: "Produce" },
  { name: "cauliflower", category: "Produce" },
  { name: "spinach", category: "Produce" },
  { name: "kale", category: "Produce" },
  { name: "lettuce", category: "Produce" },
  { name: "romaine lettuce", category: "Produce" },
  { name: "cucumber", category: "Produce" },
  { name: "bell pepper", category: "Produce" },
  { name: "jalapeno", category: "Produce" },
  { name: "mushrooms", category: "Produce" },
  { name: "zucchini", category: "Produce" },
  { name: "corn", category: "Produce" },
  { name: "green beans", category: "Produce" },
  { name: "asparagus", category: "Produce" },
  { name: "cabbage", category: "Produce" },
  { name: "cilantro", category: "Produce" },
  { name: "basil", category: "Produce" },
  { name: "parsley", category: "Produce" },
  { name: "green onions", category: "Produce" },
  { name: "watermelon", category: "Produce" },
  { name: "pineapple", category: "Produce" },
  { name: "mango", category: "Produce" },
  { name: "peaches", category: "Produce" },

  // Meat & Seafood
  { name: "chicken breast", category: "Meat & Seafood" },
  { name: "chicken thighs", category: "Meat & Seafood" },
  { name: "whole chicken", category: "Meat & Seafood" },
  { name: "ground beef", category: "Meat & Seafood" },
  { name: "ground turkey", category: "Meat & Seafood" },
  { name: "steak", category: "Meat & Seafood" },
  { name: "pork chops", category: "Meat & Seafood" },
  { name: "pork tenderloin", category: "Meat & Seafood" },
  { name: "bacon", category: "Meat & Seafood" },
  { name: "sausage", category: "Meat & Seafood" },
  { name: "ham", category: "Meat & Seafood" },
  { name: "turkey", category: "Meat & Seafood" },
  { name: "salmon", category: "Meat & Seafood" },
  { name: "shrimp", category: "Meat & Seafood" },
  { name: "tuna", category: "Meat & Seafood" },
  { name: "tilapia", category: "Meat & Seafood" },
  { name: "deli meat", category: "Meat & Seafood" },
  { name: "hot dogs", category: "Meat & Seafood" },

  // Bakery
  { name: "bread", category: "Bakery" },
  { name: "whole wheat bread", category: "Bakery" },
  { name: "sourdough bread", category: "Bakery" },
  { name: "bagels", category: "Bakery" },
  { name: "english muffins", category: "Bakery" },
  { name: "tortillas", category: "Bakery" },
  { name: "pita bread", category: "Bakery" },
  { name: "hamburger buns", category: "Bakery" },
  { name: "hot dog buns", category: "Bakery" },
  { name: "croissants", category: "Bakery" },
  { name: "muffins", category: "Bakery" },
  { name: "donuts", category: "Bakery" },

  // Frozen
  { name: "frozen pizza", category: "Frozen" },
  { name: "ice cream", category: "Frozen" },
  { name: "frozen vegetables", category: "Frozen" },
  { name: "frozen fruit", category: "Frozen" },
  { name: "frozen waffles", category: "Frozen" },
  { name: "frozen chicken nuggets", category: "Frozen" },
  { name: "frozen fries", category: "Frozen" },
  { name: "frozen burritos", category: "Frozen" },

  // Canned Goods
  { name: "canned tomatoes", category: "Canned Goods" },
  { name: "tomato sauce", category: "Canned Goods" },
  { name: "tomato paste", category: "Canned Goods" },
  { name: "canned beans", category: "Canned Goods" },
  { name: "black beans", category: "Canned Goods" },
  { name: "kidney beans", category: "Canned Goods" },
  { name: "chickpeas", category: "Canned Goods" },
  { name: "canned corn", category: "Canned Goods" },
  { name: "canned tuna", category: "Canned Goods" },
  { name: "chicken broth", category: "Canned Goods" },
  { name: "vegetable broth", category: "Canned Goods" },
  { name: "coconut milk", category: "Canned Goods" },
  { name: "soup", category: "Canned Goods" },

  // Snacks
  { name: "chips", category: "Snacks" },
  { name: "tortilla chips", category: "Snacks" },
  { name: "pretzels", category: "Snacks" },
  { name: "popcorn", category: "Snacks" },
  { name: "crackers", category: "Snacks" },
  { name: "granola bars", category: "Snacks" },
  { name: "trail mix", category: "Snacks" },
  { name: "nuts", category: "Snacks" },
  { name: "almonds", category: "Snacks" },
  { name: "peanuts", category: "Snacks" },
  { name: "cookies", category: "Snacks" },
  { name: "chocolate", category: "Snacks" },

  // Beverages
  { name: "water", category: "Beverages" },
  { name: "sparkling water", category: "Beverages" },
  { name: "orange juice", category: "Beverages" },
  { name: "apple juice", category: "Beverages" },
  { name: "coffee", category: "Beverages" },
  { name: "tea", category: "Beverages" },
  { name: "green tea", category: "Beverages" },
  { name: "soda", category: "Beverages" },
  { name: "beer", category: "Beverages" },
  { name: "wine", category: "Beverages" },
  { name: "energy drinks", category: "Beverages" },
  { name: "kombucha", category: "Beverages" },

  // Condiments
  { name: "ketchup", category: "Condiments" },
  { name: "mustard", category: "Condiments" },
  { name: "mayonnaise", category: "Condiments" },
  { name: "hot sauce", category: "Condiments" },
  { name: "soy sauce", category: "Condiments" },
  { name: "salsa", category: "Condiments" },
  { name: "olive oil", category: "Condiments" },
  { name: "vegetable oil", category: "Condiments" },
  { name: "vinegar", category: "Condiments" },
  { name: "honey", category: "Condiments" },
  { name: "maple syrup", category: "Condiments" },
  { name: "peanut butter", category: "Condiments" },
  { name: "jelly", category: "Condiments" },
  { name: "jam", category: "Condiments" },
  { name: "ranch dressing", category: "Condiments" },
  { name: "salad dressing", category: "Condiments" },
  { name: "bbq sauce", category: "Condiments" },

  // Grains & Pasta
  { name: "rice", category: "Grains & Pasta" },
  { name: "brown rice", category: "Grains & Pasta" },
  { name: "pasta", category: "Grains & Pasta" },
  { name: "spaghetti", category: "Grains & Pasta" },
  { name: "penne", category: "Grains & Pasta" },
  { name: "macaroni", category: "Grains & Pasta" },
  { name: "flour", category: "Grains & Pasta" },
  { name: "sugar", category: "Grains & Pasta" },
  { name: "brown sugar", category: "Grains & Pasta" },
  { name: "oats", category: "Grains & Pasta" },
  { name: "oatmeal", category: "Grains & Pasta" },
  { name: "cereal", category: "Grains & Pasta" },
  { name: "granola", category: "Grains & Pasta" },
  { name: "quinoa", category: "Grains & Pasta" },
  { name: "couscous", category: "Grains & Pasta" },
  { name: "pancake mix", category: "Grains & Pasta" },
  { name: "baking powder", category: "Grains & Pasta" },
  { name: "baking soda", category: "Grains & Pasta" },
  { name: "cornstarch", category: "Grains & Pasta" },
  { name: "breadcrumbs", category: "Grains & Pasta" },

  // Other
  { name: "paper towels", category: "Other" },
  { name: "toilet paper", category: "Other" },
  { name: "dish soap", category: "Other" },
  { name: "laundry detergent", category: "Other" },
  { name: "trash bags", category: "Other" },
  { name: "aluminum foil", category: "Other" },
  { name: "plastic wrap", category: "Other" },
  { name: "zip lock bags", category: "Other" },
  { name: "salt", category: "Other" },
  { name: "pepper", category: "Other" },
  { name: "cinnamon", category: "Other" },
  { name: "cumin", category: "Other" },
  { name: "paprika", category: "Other" },
  { name: "garlic powder", category: "Other" },
  { name: "onion powder", category: "Other" },
  { name: "chili powder", category: "Other" },
  { name: "italian seasoning", category: "Other" },
];

export const GROCERY_ITEM_NAMES = GROCERY_ITEMS.map((item) => item.name);

export default GROCERY_ITEMS;
